# https://github.com/kuroski/github-issue-viewer/blob/main/docker-compose.yml

version: "3.9"

services:
  db:
    image: mysql:oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    healthcheck:
      test: curl --fail http://127.0.0.1:3306/ping || exit 1
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
