# https://github.com/kuroski/github-issue-viewer/blob/main/docker-compose.yml

version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=improvdb_user
      - POSTGRES_DB=improvdb_db
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u improvdb_user"]
      interval: 2s
      timeout: 5s
      retries: 20

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
