# Use the Playwright base image (includes Node) to avoid duplicate bases and reduce vulnerabilities
FROM mcr.microsoft.com/playwright:v1.58.0-jammy
 
# Set the work directory for the application
WORKDIR /app
 
# Set the environment path to node_modules/.bin
ENV PATH=/app/node_modules/.bin:$PATH
ENV TEST_ENV=docker

# COPY the needed files to the app folder in Docker image
COPY package.json /app/
COPY package-lock.json /app/
COPY tsconfig.json /app/
COPY prisma/ /app/prisma/

# Install the dependencies in Node environment
RUN npm ci

# Copy playwright config
COPY playwright.config.ts /app/
