name: Lint & Type Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  DATABASE_URL: "https://fake.com"
  NODE_ENV: "test"

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
